### PR TITLE
Added some details to README.md and created CONTRIBUTING.md

### PR DESCRIPTION
**Pull request by SiAust**
A little added to the `README.md` just until we become more specific with our goals and features.

The OU info was generated by Bard AI. I tried to cite it using the syntax I thought most appropriate but it does not seem to render the asterisk bullet list at the bottom, as I thought it should.

[Markdown Referencing Syntax](https://www.markdownguide.org/basic-syntax/#reference-style-links)

### CODE REVIEW

**Review by marek-jakub — APPROVED** [review]

**Comment by marek-jakub** [comment]
Yes, .md with its quirks. Maybe you could try something similar to:
https://stackoverflow.com/questions/26587527/cite-a-paper-using-github-markdown-syntax

Do you want to create links in the text, or show references as well?

Something like:

```
their own pace and from anywhere in the world, with the support of a network of regional centers and online resources." [[1]](#1)

### References
<a id="1">[1] </a>https://g.co/bard/share/05329cf739e6 "Bard, a large language model created by Google AI."
```

**Comment by SiAust** [comment]
I was going for a reference style list like we do with assignments but it's not really needed. As long as people understand where the text came from, Bard in this case, a link would do I suppose. 

Interesting code, I will try it out! Do you want me to update the code branch?

Edit: That code didn't quite work right either but I've found some that should, at least on Github. It doesn't format properly in InteliJ Idea Markdown viewer but if I push to the repo apparently it should on Github. [Markdown Footnotes](https://docs.github.com/en/get-started/writing-on-github/getting-started-with-writing-and-formatting-on-github/basic-writing-and-formatting-syntax#footnotes)

Edit2: It does work on Github \o/

**Comment by marek-jakub** [comment]
Thanks Simon, I'll leave it up to you, you've done a grand job, a link should suffice. We will need to keep updating it, anyway.

**Comment by SiAust** [comment]
Yeah absolutely, just a little practice and exploring more markdown features is always fun.

 I guess we can go ahead and merge this one? I know I did the code review request but that was also for practice/test purposes really. Ok to go ahead @farmeroy ? :)

**Pull request merged**
